unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Welcome to the current millenium
set nocompatible
set term=xterm-256color
set t_Co=256
set t_ut=
syntax on
set showcmd

colorscheme badwolf

" LINE NUMBERS:
set rnu nu
set colorcolumn=80,120
set cursorline
"hi CursorLine cterm=NONE ctermbg=17 ctermfg=NONE
"hi CursorLineNr term=bold cterm=bold ctermfg=012 gui=bold
hi CursorLineNr term=bold cterm=bold gui=bold

" AUTOCOMPLETION:
set path+=**
set wildmenu

" GENERAL:
set smartindent autoindent
set incsearch hlsearch " :nohlsearch
set hidden

" INVISIBLE CHARS:
"let &listchars="eol:↲,tab: ,space:·,lead:·,trail:~,extends:>,precedes:<,"
set listchars=eol:↲,tab:\ ,space:·,lead:\·,trail:~,extends:>,precedes:<,
"set listchars=space:·,trail:·,precedes:«,extends:»,eol:↲,tab:\ 
set list
hi NonText ctermfg=8
hi SpecialKey ctermfg=8

" SNIPPETS:
nnoremap ,html :-1read $HOME/.vim/skeleton/html<CR>5jf>a

command! MakeTags !ctags -R .

set tabstop=4 shiftwidth=4 expandtab
set conceallevel=3
set spelllang=de,en spell

command! MakeTags !ctags -R .

if has('gui_running')
    nnoremap <silent> <Esc> :
else
    augroup escape_mapping
        autocmd TermResponse * nnoremap <Esc> :
    augroup END
end

"nmap <ESC> :
